name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Dic0
          outputs: |
            dist/github-contribution-grid-snake.svg
      - name: Commit animation
        uses: EndBug/add-and-commit@v9
        with:
          message: "generated snake animation"
          add: "dist/github-contribution-grid-snake.svg"
      - name: Push to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
