name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: Dic0
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Ajustar SVG para fundo transparente e bordas
        run: |
          # Deixa os quadradinhos sem fundo
          sed -i 's/fill:var(--ce);/fill:none;/g' dist/github-contribution-grid-snake.svg

          # Borda branca mais fina
          sed -i 's/stroke-width:1px;/stroke-width:0.5px;/g' dist/github-contribution-grid-snake.svg
          sed -i 's/stroke:var(--cb);/stroke:#383636d1;/g' dist/github-contribution-grid-snake.svg

          # Remove os fills dos quadradinhos com commits (cores)
          sed -i 's/fill:var(--c[0-4]);/fill:none;/g' dist/github-contribution-grid-snake.svg
          sed -i 's/fill:var(--c[0-4][a-z]*);/fill:none;/g' dist/github-contribution-grid-snake.svg
          sed -i 's/{fill:var(--c[0-4]);/{fill:none;/g' dist/github-contribution-grid-snake.svg
          sed -i 's/{fill:var(--c[0-4][a-z]*);/{fill:none;/g' dist/github-contribution-grid-snake.svg

          # Ajusta os keyframes para que os quadrados fiquem transparentes depois que a cobrinha passa
          sed -i 's/fill:var(--ce)/fill:none/g' dist/github-contribution-grid-snake.svg
          sed -i 's/55.12%,100%{fill:var(--ce)}/55.12%,100%{fill:none}/g' dist/github-contribution-grid-snake.svg
          sed -i 's/25.79%,100%{fill:var(--ce)}/25.79%,100%{fill:none}/g' dist/github-contribution-grid-snake.svg
          sed -i 's/24.9%,100%{fill:var(--ce)}/24.9%,100%{fill:none}/g' dist/github-contribution-grid-snake.svg
          sed -i 's/60.9%,100%{fill:var(--ce)}/60.9%,100%{fill:none}/g' dist/github-contribution-grid-snake.svg
          sed -i 's/14.23%,100%{fill:var(--ce)}/14.23%,100%{fill:none}/g' dist/github-contribution-grid-snake.svg
          sed -i 's/11.57%,100%{fill:var(--ce)}/11.57%,100%{fill:none}/g' dist/github-contribution-grid-snake.svg
          sed -i 's/20.45%,100%{fill:var(--ce)}/20.45%,100%{fill:none}/g' dist/github-contribution-grid-snake.svg
          sed -i 's/18.23%,100%{fill:var(--ce)}/18.23%,100%{fill:none}/g' dist/github-contribution-grid-snake.svg
          sed -i 's/35.57%,100%{fill:var(--ce)}/35.57%,100%{fill:none}/g' dist/github-contribution-grid-snake.svg
          sed -i 's/38.68%,100%{fill:var(--ce)}/38.68%,100%{fill:none}/g' dist/github-contribution-grid-snake.svg
          sed -i 's/74.23%,100%{fill:var(--ce)}/74.23%,100%{fill:none}/g' dist/github-contribution-grid-snake.svg
          sed -i 's/74.68%,100%{fill:var(--ce)}/74.68%,100%{fill:none}/g' dist/github-contribution-grid-snake.svg

      - name: Commit animation
        uses: EndBug/add-and-commit@v9
        with:
          message: "generated snake animation"
          add: "dist/github-contribution-grid-snake.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
