name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set theme variables
        id: theme-vars
        run: |
          TODAY=$(date +%m-%d)
          if [ "$TODAY" = "12-25" ]; then
            echo "color_snake=#d90429" >> $GITHUB_OUTPUT       # Natal
            echo "color_border=#a4133c" >> $GITHUB_OUTPUT
            echo "emoji=🎅🏼" >> $GITHUB_OUTPUT
          elif [ "$TODAY" = "10-31" ]; then
            echo "color_snake=#ff6f59" >> $GITHUB_OUTPUT       # Halloween
            echo "color_border=#3d3d3d" >> $GITHUB_OUTPUT
            echo "emoji=🎃" >> $GITHUB_OUTPUT
          elif [ "$TODAY" = "12-31" ]; then
            echo "color_snake=#ffe066" >> $GITHUB_OUTPUT       # Ano Novo
            echo "color_border=#ffd60a" >> $GITHUB_OUTPUT
            echo "emoji=✨" >> $GITHUB_OUTPUT
          elif [ "$TODAY" = "08-20" ]; then
            echo "color_snake=#ff007f" >> $GITHUB_OUTPUT       # Aniversário
            echo "color_border=#ffffff" >> $GITHUB_OUTPUT
            echo "emoji=🎂" >> $GITHUB_OUTPUT
          else
            echo "color_snake=purple" >> $GITHUB_OUTPUT
            echo "color_border=#ffffff" >> $GITHUB_OUTPUT
            echo "emoji=" >> $GITHUB_OUTPUT
          fi

      - uses: Platane/snk@v3
        with:
          github_user_name: Dic0
          outputs: dist/github-contribution-grid-snake.svg

      - name: Personalizar SVG
        run: |
          FILE="dist/github-contribution-grid-snake.svg"
          COLOR_SNAKE="${{ steps.theme-vars.outputs.color_snake }}"
          COLOR_BORDER="${{ steps.theme-vars.outputs.color_border }}"

          # Cobrinha: mudar cor
          sed -i "s/fill:purple;/fill:${COLOR_SNAKE};/g" "$FILE"

          # Quadradinhos sem commit: manter transparentes
          sed -i 's/fill:var(--ce);/fill:none;/g' "$FILE"
          sed -i 's/fill:var(--c[0-4]);/fill:none;/g' "$FILE"
          sed -i 's/fill:var(--c[0-4][a-z]*);/fill:none;/g' "$FILE"
          sed -i 's/{fill:var(--c[0-4]);/{fill:none;/g' "$FILE"
          sed -i 's/{fill:var(--c[0-4][a-z]*);/{fill:none;/g' "$FILE"

          # Bordas nos quadradinhos
          sed -i "s/stroke:var(--cb);/stroke:${COLOR_BORDER};/g" "$FILE"
          sed -i 's/stroke-width:1px;/stroke-width:0.5px;/g' "$FILE"

      - name: Substituir commits por emojis nos dias especiais
        if: ${{ steps.theme-vars.outputs.emoji != '' }}
        run: |
          node <<EOF
          const fs = require('fs');
          const file = 'dist/github-contribution-grid-snake.svg';
          const emoji = "${{ steps.theme-vars.outputs.emoji }}";
          let svg = fs.readFileSync(file, 'utf8');
          svg = svg.replace(/<rect class="c"[^>]*x="([\d.]+)"[^>]*y="([\d.]+)"[^>]*width="([\d.]+)"[^>]*height="([\d.]+)"[^>]*\/>/g,
            (match, x, y, w, h) => {
              const fontSize = Math.min(parseFloat(w), parseFloat(h));
              const adjustedX = parseFloat(x) + fontSize / 2;
              const adjustedY = parseFloat(y) + fontSize * 0.75;
              return `<text x="${adjustedX}" y="${adjustedY}" font-size="${fontSize}" text-anchor="middle">${emoji}</text>`;
            });
          fs.writeFileSync(file, svg);
          EOF

      - name: Bordas arco-íris no aniversário
        if: ${{ steps.theme-vars.outputs.color_snake == '#ff007f' }}
        run: |
          node <<EOF
          const fs = require('fs');
          const path = 'dist/github-contribution-grid-snake.svg';
          const rainbow = ['#ff0000','#ff7f00','#ffff00','#00ff00','#0000ff','#4b0082','#8a2be2','#ff1493'];
          let svg = fs.readFileSync(path, 'utf8');
          let i = 0;
          svg = svg.replace(/stroke="#ffffff"/g, () => {
            const c = rainbow[i % rainbow.length];
            i++;
            return `stroke="${c}"`;
          });
          fs.writeFileSync(path, svg);
          EOF

      - name: Commit animation
        uses: EndBug/add-and-commit@v9
        with:
          message: "generated snake animation"
          add: "dist/github-contribution-grid-snake.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
