name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: Dic0
          outputs: |
            dist/github-contribution-grid-snake.svg
            svg_configuration: '{"color_empty":"transparent","color_0":"transparent","color_1":"transparent","color_2":"transparent","color_3":"transparent","color_4":"transparent","color_border":"#ffffffaa","color_snake":"purple"}'

      - name: Commit animation
        uses: EndBug/add-and-commit@v9
        with:
          message: "generated snake animation"
          add: "dist/github-contribution-grid-snake.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
